microsoft/playwright-test

packages/e2e/package.json, packages/superpowers/package.json, packages/unit/package.json
Once we hit 1.0 this should stop being necessarily until 2.0 or we require new playwright features.
=> upgrade playwright to 0.14.0

package.json
Something in Jest depends on these types, but doesn't ship them to us.
=> fix: add types for graceful-fs

packages/e2e/src/index.ts
After https://github.com/facebook/jest/pull/9855, jest complains about our require magic. This only effects our internal tests. Jest already clears the cache between each run for us. It is ok to just disable the code.
=> fix(test): suppress jest require cache warning

packages/e2e/package.json, packages/superpowers/package.json, packages/unit/package.json
Maybe it makes sense to exclude `playwright` entirely from the project as we did in `jest-playwright`? So only playwright-core will be used for types.
So the user can decide which browser / npm package he wants to install in the end to save bandwidth. (`playwright` vs. `playwright-chromium` etc.)
Disadvantage for that is definitely that sometimes it can lead to issues if `playwright-runner` is not compatible with the latest Playwright version.
=> bump: Playwright to 0.16.0

packages/e2e/tests/assets/twoTests.js, packages/e2e/tests/mock.spec.js
The beforeEach hooks have different semantics because state is copied instead of just passed into the next test.
=> fix mock test

.github/workflows/test-examples.yml, .gitignore, README.md, examples/.gitignore, examples/basic-js/package.json, examples/basic-js/tests/playwright.spec.js, examples/basic-ts/package.json, examples/basic-ts/tests/playwright.spec.ts, examples/browser-device-matrix/package.json, examples/browser-device-matrix/test/playwright.spec.ts, examples/browser-device-matrix/test/setup.ts, examples/record-video/package.json, examples/record-video/tests/playwright.spec.ts, examples/screenshot-on-failure/package.json, examples/screenshot-on-failure/tests/playwright.spec.ts
Action items out of that for the future:
- Replace screen recording by native solution (in a few months)
- Abstract the logic for generating an output file replace / by - with test path + test name. Maybe add it to the test object.
- Page.screenshot lets maybe add directory creation to it like we do with Download.save?
We decided offline to not implement "screenshot on failure" directly so I would only add a general helper function for easier test-results generation.
We have to evaluate carefully which of these scenarios should be implemented natively to not end up in a bloated project.
Try to follow up with:
- Improve somehow the typings
- add docs for fixture / types
- add docs about setup.ts
=> docs: added basic examples

.github/workflows/test-examples.yml, examples/browser-device-matrix/test/playwright.spec.ts, examples/browser-device-matrix/test/setup.ts, examples/record-video/tests/playwright.spec.ts, examples/screenshot-on-failure/tests/playwright.spec.ts, packages/playwright-runner/src/index.ts, packages/test-runner/src/cli.ts, packages/test-runner/src/fixtures.ts, packages/test-runner/src/index.ts
Maybe only allow TypeScript and fully drop JavaScript support?
Moved deviceName handling also into the playwright runner project.
=> feat: abstracted asset generation logic

.github/workflows/main.yml, .github/workflows/test-examples.yml, README.md, examples/basic-ts/tests/playwright.spec.ts, examples/browser-device-matrix/test/playwright.spec.ts, examples/record-video/tests/playwright.spec.ts, examples/screenshot-on-failure/tests/playwright.spec.ts, packages/playwright-runner/README.md, packages/test-runner/src/cli.ts, packages/test-runner/test/assets/is-not-defined-error.ts, packages/test-runner/test/exit-code.spec.ts, packages/test-runner/test/fixtures.ts
Drive-by: Use tip-of-tree version of test-runner to test the test-runner instead of the version on NPM.
=> fix: exit code on parse error

packages/test-runner/src/index.ts, packages/test-runner/src/spec.ts, packages/test-runner/test/assets/export-type-only.fixtures.ts, packages/test-runner/test/assets/export-wrap.fixtures.ts, packages/test-runner/test/assets/fixture-timeout.js, packages/test-runner/test/assets/import-fixtures-both.ts, packages/test-runner/test/assets/import-fixtures-type-only.ts, packages/test-runner/test/assets/import-fixtures-wrap.ts, packages/test-runner/test/assets/test-data-visible-in-fixture.ts, packages/test-runner/test/assets/test-error-visible-in-fixture.ts, packages/test-runner/test/types.spec.ts
See tests for example use:
- `export-wrap.fixtures` and `import-fixtures-wrap` define a full-scale wrapper around a test runner;
- `export-type-only.fixtures` and `import-fixtures-type-only` define a lightweight fixtures pack with types;
- `import-fixtures-both` uses both.
=> types: switch from declare global to explicit templates

.github/workflows/test-examples.yml, packages/test-runner/test/fixtures.ts
Fixes the issue that Playwright Runner has used the test runner from node modules. That lead to inconsistency that the version from NPM was used.
=> fix: examples on bots

examples/browser-device-matrix/package.json, packages/test-runner/src/cli.ts, packages/test-runner/test/exit-code.spec.ts
Currently we log on errors in the try/catch block the whole error including stack trace. This might be confusing for the user, should we maybe only log the error.toString() instead?
Example that missing dir/file will return a 0: https://github.com/microsoft/playwright-runner/runs/1076478989#step:11:5
=> fix: exit with 1 if test dir/file does not exist

packages/test-runner/tsconfig.json
the test-runner runs in node, so it should not need the dom typings. We can't change playwright-testrunner because playwright needs dom types for element handles.
=> fix(types): don't depend on the dom types for test-runner

package.json, packages/playwright-runner/package.json, packages/test-runner/package.json, scripts/checkVersions.js, scripts/lintPackages.js, scripts/updateVersion.js, stable-test-runner/package.json, stable-test-runner/yarn.lock
Having the test-runner depend on the stable version of itself was not working properly. It broke typechecking, and the `playwright-runner` package was incorrectly depending on the stable version of the runner. This adds a `stable-test-runner` folder where the version of the test runner on npm is installed as normal. Then it is linked to via a file install.
The version mismatch between the two packages was also breaking things. I updated it to 0.3.5 and added a lint to make sure they don't get out of sync.
=> fix: properly depend on the stable test runner

package.json, packages/test-runner/src/fixtures.ts, packages/test-runner/src/testCollector.ts, packages/test-runner/src/testRunner.ts, yarn.lock
clears the fixture registry before re-registering fixtures. This means that fixtures cannot leak into tests that don't require them.
Also fixes a bug where fixture locations were corrupted by `source-map-support`.
=> fix(fixtures): isolate fixtures between files

packages/test-runner/package.json, packages/test-runner/src/transform.ts, yarn.lock
Adds types for @babel/core and fixes the sourcemap option to append a sourceMappingURL comment.
=> fix(sourcemaps): fix sourcemaps when debugging tests

packages/test-runner/src/cli.ts, packages/test-runner/src/reporter.ts, packages/test-runner/src/reporters/base.ts, packages/test-runner/src/reporters/json.ts, packages/test-runner/src/reporters/multiplexer.ts, packages/test-runner/src/runner.ts, packages/test-runner/test/exit-code.spec.ts, packages/test-runner/test/fixtures.ts, packages/test-runner/test/parameters.spec.ts, packages/test-runner/test/register-parameter.spec.ts
This patch adds `onLoadingFailure` to the reporter api. It is fired when a test suite has an error upon being required. It appears in the report json as `loadingFailure`. Previously, no report would be generated.
Drive-by changes: JSONReporter no longer extends BaseReporter. The JSON report format is now typed.
=> feat(error): report toplevel fire errors

packages/test-runner/src/fixtures.ts, packages/test-runner/src/runner.ts, packages/test-runner/src/test.ts, packages/test-runner/src/testCollector.ts, packages/test-runner/test/fixtures.spec.ts
depends on #115 
This uses babel instead of a regular expression to parse the first parameter of a function that uses fixtures. It also refactors the test collector to allow reporting a `parseError` when the argument cannot be parsed.
=> fix(fixtures): use babel to parse dependencies

packages/test-runner/src/dispatcher.ts, packages/test-runner/src/fixtures.ts, packages/test-runner/src/index.ts, packages/test-runner/src/runner.ts, packages/test-runner/src/runnerTest.ts, packages/test-runner/src/test.ts, packages/test-runner/src/testGenerator.ts, packages/test-runner/src/testModifier.ts, packages/test-runner/src/worker.ts, packages/test-runner/src/workerRunner.ts, packages/test-runner/src/workerTest.ts, packages/test-runner/test/assets/register-parameter.ts, packages/test-runner/test/assets/test-data-visible-in-fixture.ts, packages/test-runner/test/assets/test-error-visible-in-fixture.ts
Possible follow up:
- move annotations from TestRun to Test;
- rename TestRun into TestResult;
- rename TestInfo into TestRun.
=> api: separate TestInfo api from Spec and friends

.github/workflows/main.yml, package-lock.json, package.json, src/index.ts
Fixes https://github.com/microsoft/playwright-test/issues/141
=> chore: roll test runner to 0.9.22

README.md
Without this, the links using this target were rendered like this:
`[BrowserContext][browser-context]`
=> Add missing link in README

examples/basic-js/package.json, examples/basic-ts/package.json, examples/login-once-per-worker/package.json, examples/screenshot-on-failure/package.json
The examples have and old reference to the test-runner for running the tests. Updated the package.json files to call `npx folio`
=> Fixed examples

src/index.ts
`PWDEBUG` is not working. This is because we always set the headful to either true or false. Allow headful to be undefined to enable `PWDEBUG`.
=> fix: type of headful param
