microsoft/playwright-test

packages/describers/src/index.ts, packages/describers/tests/describers.spec.js, packages/e2e/src/globals.ts, packages/e2e/src/index.ts, packages/e2e/tests/assets/twoTests.js, packages/unit/src/index.ts, packages/unit/web/root.html
TestWorker is capable of running one more test, and will be a centerpiece of the parallel execution.
=> feat(describers): introduce TestWorker, implement beforeAll/afterAll

packages/demo/e2e/page.spec.js, packages/demo/playwright.config.js, packages/describers/src/index.ts, packages/e2e/src/index.ts, packages/e2e/tests/assets/onlyChrome.js, packages/e2e/tests/assets/playwright.config.js, packages/e2e/tests/fakeJestRun.ts, packages/e2e/tests/mock.spec.js
=> feat(e2e): playwright.config and multiple browsers

packages/describers/src/index.ts, packages/e2e/src/index.ts
=> feat(e2e): parallel execution

packages/describers/src/index.ts, packages/describers/tests/describers.spec.js, packages/e2e/src/globals.ts, packages/e2e/src/index.ts, packages/e2e/tests/assets/focusedTest.js, packages/e2e/tests/fakeJestRun.ts, packages/e2e/tests/mock.spec.js, packages/unit/src/index.ts, packages/unit/web/root.html
=> feat: focused and skipped tests

packages/demo/jest.config.js, packages/describers/src/index.ts, packages/describers/src/runner.ts, packages/e2e/src/index.ts, packages/e2e/tests/assets/twoTests.js, packages/jest-wrapper/src/index.ts, packages/playwright-runner/jest-preset.js, packages/playwright-runner/package.json, packages/playwright-runner/src/index.ts, packages/playwright-runner/tsconfig.json, tsconfig.json
Describer environments
Filtering in the jest wrapper
todo tests in the jest wrapper
playwright-runner only has e2e in its preset
=> Fixup jest wrapper

packages/playwright-runner/jest-preset.js, packages/playwright-runner/package.json
The unit runner isn't a priority right now.
=> remove unit runner from playwright-runner

package.json, packages/demo/package.json, packages/describers/package.json, packages/describers/src/expect.ts, packages/describers/src/index.ts, packages/describers/src/test.ts, packages/e2e/package.json, packages/jest-wrapper/package.json, packages/jest-wrapper/src/index.ts, packages/playwright-runner/package.json, packages/playwright-runner/src/index.ts
=> update to version 0.1.0

packages/test-runner/src/builtin.fixtures.ts, packages/test-runner/src/index.ts, packages/test-runner/src/reporters/base.ts, packages/test-runner/src/reporters/dot.ts, packages/test-runner/src/reporters/json.ts, packages/test-runner/src/reporters/list.ts, packages/test-runner/src/reporters/pytest.ts, packages/test-runner/src/runner.ts, packages/test-runner/src/spec.ts, packages/test-runner/src/test.ts, packages/test-runner/src/testCollector.ts, packages/test-runner/src/testRunner.ts, packages/test-runner/src/worker.ts, packages/test-runner/test/assets/expected-failure.js, packages/test-runner/test/assets/nested-skip.js, packages/test-runner/test/assets/one-failure.js, packages/test-runner/test/assets/one-success.js, packages/test-runner/test/assets/one-timeout.js, packages/test-runner/test/assets/unexpected-pass.js, packages/test-runner/test/assets/unhandled-rejection.js, packages/test-runner/test/exit-code.spec.ts
playwright hash: https://github.com/microsoft/playwright/commit/c47af2d4f3750ecf40f26d1513fc1ae1b8fbe6d4
=> roll test runner to august 28

packages/test-runner/src/cli.ts, packages/test-runner/test/assets/slow.js
Drive-by: automatically generate available reporter list.
=> feat: use list reporter by default

packages/test-runner/src/transform.ts
Docs: https://babeljs.io/docs/en/babel-preset-env#targetsnode
=> fix(test-runner): specify target Node.js version

packages/test-runner/src/reporters/base.ts
=> fix(reporter): duration when interrupted

README.md
=> Fixed example path on README.md

packages/test-runner/test/fixtures.spec.ts, packages/test-runner/test/fixtures.ts
`runMiniTest` defines a set of files inline and runs the test-runner on them.
=> test: add runMiniTest and some fixtures tests

README.md
=> docs(readme): spec syntax and assertions

README.md
=> docs(readme): assertions for visual comparisons

README.md
=> docs(readme): skip with annotations

README.md
=> docs(readme): fix parameters link

docs/auth.md, docs/network.md, docs/setup-teardown.md
Closes #178
Closes #179 
Closes #180
=> docs: add setup-teardown, network and auth docs

README.md, examples/basic-js/package.json, examples/basic-js/tests/test.spec.js, examples/basic-ts/package.json, examples/basic-ts/tests/test.spec.ts, examples/login-once-per-worker/package.json, examples/screenshot-on-failure/package.json, examples/screenshot-on-failure/tests/test.spec.ts
=> fix(examples): update and fix screenshot example

package.json
Should resolve #210 by [ignoring babelrc](https://github.com/microsoft/folio/commit/3d1fb21b5f2c460a46aa895aa8c551c3c22acc2b).
=> chore: roll to playwright@1.8.1, folio to 0.3.18

src/index.ts
=> fix: use of headful parameter

README.md, package.json
=> chore: mark 0.1101 and roll to folio@0.3.23-alpha
